services:
  novinki-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_BASE_PATH: ""
        NEXT_PUBLIC_STORAGE_DRIVER: "filesystem"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - novinki-data:/app/data
      - novinki-uploads:/app/uploads
    env_file:
      - .env
    environment:
      NODE_ENV: production
      SQLITE_DB_PATH: /app/data/novinki.db
      UPLOAD_DIR: /app/uploads
      NEXT_PUBLIC_STORAGE_DRIVER: filesystem

volumes:
  novinki-data:
  novinki-uploads:
