/** Demo mode: mock data used when NEXT_PUBLIC_DEMO_MODE=true */

export const DEMO_ADMIN_EMAIL = 'admin@demo.ru'
export const DEMO_ADMIN_PASSWORD = 'admin1234'

export const DEMO_USERS = [
  { id: 'demo-admin-001', email: DEMO_ADMIN_EMAIL, is_admin: true, name: 'Demo Admin' },
  { id: 'demo-user-001', email: 'user@demo.ru', is_admin: false, name: 'Demo User' },
]

const img = (seed: string) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/400/300`

export const DEMO_PRODUCTS_INITIAL = [
  {
    id: 'dp-001',
    name: 'Аккумуляторная дрель-шуруповёрт GSR 12V-35',
    brand: 'Bosch',
    article_number: 'BSH-GSR12V-001',
    description: 'Компактная аккумуляторная дрель-шуруповёрт нового поколения. Мощность 35 Нм, скорость вращения 0-420/0-1400 об/мин, 2 режима работы.',
    image_url: img('bosch-drill'),
    advantages: 'Малый вес 0.9 кг, 2 аккумулятора 12V в комплекте, быстрый заряд за 45 мин, патрон 10 мм.',
    attention_points: 'Подходит только для лёгких работ. Не предназначен для ударного сверления твёрдых материалов.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Электроинструмент',
    rating: 4.7,
    price: 8500,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-002',
    name: 'Угловая шлифмашина WS 125-S',
    brand: 'Bosch',
    article_number: 'BSH-WS125S-002',
    description: 'Профессиональная угловая шлифмашина 125 мм, мощность 1200 Вт, число оборотов 11 000 об/мин.',
    image_url: img('angle-grinder'),
    advantages: 'Мощный двигатель, вибро-защита рукоятки, быстрый зажим диска без ключа.',
    attention_points: 'Обязательно использовать защитный кожух и очки. Работать только с дисками подходящего диаметра.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Электроинструмент',
    rating: 4.5,
    price: 6200,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-003',
    name: 'Перфоратор GBH 2-26 DRE Professional',
    brand: 'Bosch',
    article_number: 'BSH-GBH226-003',
    description: 'Профессиональный перфоратор с системой SDS Plus. Мощность 800 Вт, сила удара 2.7 Дж, 3 режима работы.',
    image_url: img('perforator'),
    advantages: 'Трёхрежимная работа (сверление/долбление/вращение+удар), защита двигателя от пыли, антивибрационная система.',
    attention_points: 'Не применять для сверления отверстий более 26 мм без специальных коронок. Регулярно смазывать хвостовики буров.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Электроинструмент',
    rating: 4.8,
    price: 14800,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-004',
    name: 'Строительный пылесос VC 35 L ADV',
    brand: 'Makita',
    article_number: 'MKT-VC35L-004',
    description: 'Строительный пылесос класса L. Объём контейнера 35 л, мощность всасывания 280 мВт, класс фильтрации HEPA.',
    image_url: img('makita-vacuum'),
    advantages: 'Автоматическая очистка фильтра, функция удалённого включения с электроинструментом, тихий режим работы.',
    attention_points: 'Не использовать для мокрого мусора без специального фильтра. Регулярно проверять заполнение контейнера.',
    website_link: 'https://makita.ru',
    onec_link: '',
    is_archived: false,
    category: 'Оборудование',
    rating: 4.3,
    price: 22000,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-005',
    name: 'Аккумуляторный шуруповёрт DDF482Z 18V',
    brand: 'Makita',
    article_number: 'MKT-DDF482-005',
    description: 'Аккумуляторный шуруповёрт серии LXT, 18 В. Мощность 62 Нм, 21+2 настройки крутящего момента.',
    image_url: img('makita-screwdriver'),
    advantages: 'Высокий крутящий момент, светодиодная подсветка рабочей зоны, эргономичная рукоятка, совместимость с АКБ LXT.',
    attention_points: 'Аккумулятор и зарядное устройство приобретаются отдельно. Не превышать допустимые диаметры оснастки.',
    website_link: 'https://makita.ru',
    onec_link: '',
    is_archived: false,
    category: 'Электроинструмент',
    rating: 4.6,
    price: 9800,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-006',
    name: 'Нивелир лазерный Cross-Line GLL 3-80 C',
    brand: 'Bosch',
    article_number: 'BSH-GLL380C-006',
    description: 'Лазерный нивелир с 3 линиями, Bluetooth управление через приложение, дальность 30 м (с приёмником 80 м).',
    image_url: img('laser-level'),
    advantages: 'Управление со смартфона, автоматическая нивелировка, точность ±0.2 мм/м, пылевлагозащита IP 54.',
    attention_points: 'Не направлять луч в глаза. Поверхность установки должна быть устойчивой. Калибровать раз в год.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Измерительный инструмент',
    rating: 4.9,
    price: 31500,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-007',
    name: 'Электролобзик T-500 Professional',
    brand: 'DeWalt',
    article_number: 'DWT-T500P-007',
    description: 'Профессиональный электролобзик. Мощность 700 Вт, ход пилки 26 мм, 4 режима маятникового движения.',
    image_url: img('jigsaw-dewalt'),
    advantages: 'Опорная плита наклоняется до 45°, быстрая замена пилок без ключа, эффективная пылезащита двигателя.',
    attention_points: 'Перед заменой пилки обязательно отключить от сети. Использовать только пилки для данной модели.',
    website_link: 'https://dewalt.ru',
    onec_link: '',
    is_archived: false,
    category: 'Электроинструмент',
    rating: 4.4,
    price: 11200,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-008',
    name: 'Рулетка самоблокирующаяся 8 м BM 40',
    brand: 'Stanley',
    article_number: 'STL-BM40-008',
    description: 'Профессиональная рулетка 8 м x 25 мм с двусторонней шкалой, крюк с магнитом, автостоп.',
    image_url: img('stanley-tape'),
    advantages: 'Магнитный крюк для одиночных замеров, ударостойкий корпус, нейлоновое покрытие ленты, разметка в мм и дюймах.',
    attention_points: 'Не использовать при температурах ниже -10°C. Не перегибать ленту под острым углом.',
    website_link: 'https://stanley.com',
    onec_link: '',
    is_archived: false,
    category: 'Ручной инструмент',
    rating: 4.2,
    price: 1850,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-009',
    name: 'Набор бит 50 мм для шуруповёрта (10 шт.)',
    brand: 'Bosch',
    article_number: 'BSH-BIT50-009',
    description: 'Набор профессиональных бит 50 мм в пластиковом контейнере: PH1, PH2, PH3, PZ1, PZ2, PZ3, T20, T25, T30, SL.',
    image_url: img('bosch-bits'),
    advantages: 'Специальная сталь S2, двойная термообработка, совместимость со всеми шуруповёртами, компактный контейнер.',
    attention_points: 'Не использовать биты с повреждённой рабочей поверхностью. Хранить в контейнере во избежание потерь.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Оснастка и расходники',
    rating: 4.6,
    price: 890,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-010',
    name: 'Строительная каска с вентиляцией 3M H-700',
    brand: '3M',
    article_number: '3M-H700-010',
    description: 'Каска строительная с системой вентиляции, регулируемым оголовьем, слот для крепления наушников и козырька.',
    image_url: img('3m-helmet'),
    advantages: 'Соответствие EN 397, 4-точечное оголовье, широкий диапазон регулировки 53-63 см, 5 цветов в ассортименте.',
    attention_points: 'Заменять каску каждые 3 года или после удара. Не хранить под прямыми солнечными лучами.',
    website_link: 'https://3m.ru',
    onec_link: '',
    is_archived: false,
    category: 'Средства защиты',
    rating: 4.3,
    price: 2400,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-011',
    name: 'Лобзиковое полотно по металлу T118B (5 шт.)',
    brand: 'Bosch',
    article_number: 'BSH-T118B-011',
    description: 'Набор пилок для электролобзика по металлу и нержавеющей стали. Шаг 1.2 мм, длина 92 мм.',
    image_url: img('jigsaw-blade'),
    advantages: 'Bi-metal конструкция, закалённые зубья, подходит для стали до 10 мм, нержавейки, алюминия.',
    attention_points: 'Работать только со средней скоростью. Использовать СОЖ при резке нержавейки.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: true,
    category: 'Оснастка и расходники',
    rating: 4.1,
    price: 650,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dp-012',
    name: 'Дальномер лазерный GLM 50-27 C',
    brand: 'Bosch',
    article_number: 'BSH-GLM5027-012',
    description: 'Лазерный дальномер дальностью 50 м с подключением к смартфону Bluetooth, встроенная камера.',
    image_url: img('bosch-rangefinder'),
    advantages: 'Встроенная камера 4x, измерение углов, вычисление площади/объёма, экспорт данных через Bluetooth.',
    attention_points: 'Не использовать на улице при ярком солнечном свете без отражателя. Калибровать перед точными работами.',
    website_link: 'https://bosch-professional.com',
    onec_link: '',
    is_archived: false,
    category: 'Измерительный инструмент',
    rating: 4.8,
    price: 18500,
    created_at: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export type DemoProduct = typeof DEMO_PRODUCTS_INITIAL[0]
